all:
	gcc -o main main.c
	
ch:
	gcc -o main main.c
	./main -ch sample1.wav saida.b

cd:
	gcc -o main main.c
	./main -cd sample1.wav saida.b

cr:
	gcc -o main main.c
	./main -cr sample1.wav saida.b

d:
	gcc -o main main.c
	./main -d saida.b final.wav

