all:
	gcc -o main main.c
	
csimples:
	gcc -o main main.c
	./main -c testeSimples.txt saida.huf

cbiblia:
	gcc -o main main.c
	./main -c Biblia.txt saida.huf
	
cinput:
	gcc -o main main.c
	./main -c input-top-grossing.txt saida.huf
des:
	gcc -o main main.c
	./main -d saida.huf saida.txt
